### ISSUE TITLE
Определить до блока if

### ISSUE THREAD

**Issue by arku31** [AdilGabdullin/php-ls-homework4#6]
Лучше определить их как переменные по умолчанию наверху.
Если условия совпадут - они перезапишутся, а блок else Будет не нужен
https://github.com/AdilGabdullin/php-ls-homework4/blob/70a4f04dce6726eba345092152a46e317d697966/php/registration.php#L40

**Comment by AdilGabdullin** [comment]
Исправил. Код стал более читабельным.
